# Dockerfile
#FROM python:3.11-slim-bullseye
#WORKDIR /frontend
#RUN python -m pip install --upgrade pip
#COPY requirements.txt requirements.txt
#RUN pip install -r requirements.txt
#ENV FLASK_APP=app
#EXPOSE 80
#COPY . .
# CMD [ "python", "backend/app.py"]